// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently
//

#pragma once

#include "targetver.h"

#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers


#define NO_VERBOSE // To control the output generated by the Parser when the Tracing is enabled

// TODO: reference additional headers your program requires here
